---
- name: Get current Ansible version on local host
  assert:
    that: "ansible_version.full | version_compare('2.8', '>=')"
    msg: "You need Ansible version 2.8.0+"

    #- name: Fail if region has less than 3 AZs
    #  assert:
    #    that: "vpc_subnet_azs | version_compare('i3', '>=')"
    #    msg: "You need Ansible version 2.2.0+"
